package com.inari.firefly.game

const val ATTR_RESOURCE = "tiledJsonResource"
const val ATTR_ENCRYPTION = "encryptionKey"
const val ATTR_TILE_SET_DIR_PATH = "tilesetDirPath"
const val ATTR_VIEW_NAME = "viewName"
const val ATTR_CREATE_LAYER = "createLayer"
const val ATTR_DEFAULT_BLEND = "defaultBlend"
const val ATTR_DEFAULT_TINT = "defaultTint"
const val ATTR_ACTIVATION_TASKS = "activationTasks"
const val ATTR_DEACTIVATION_TASKS = "deactivationTasks"
const val ATTR_ACTIVATION_SCENE = "activationScene"
const val ATTR_DEACTIVATION_SCENE = "deactivationScene"
const val ATTR_TILESET_OVERRIDE_PREFIX = "tsOverride-"

const val ATTR_TILE_SET_NAME = "tileSetName"
const val ATTR_MAPPING_START_TILE_ID = "mappingStartTileId"
const val ATTR_APPLY_TILE_SET_GROUPS = "applyTileSetGroups"
const val ATTR_APPLY_ANIMATION_GROUPS = "applyAnimationGroups"
const val NULL_VALUE = "-"
const val ATTR_TARGET_FILE = "targetFile"

const val NAME_DEFAULT_TRANSITION_BUILD_TASK = "RoomTransitionBuildTask"

const val ATTR_OBJECT_ID = "id"
const val ATTR_OBJECT_TYPE = "type"
const val ATTR_OBJECT_NAME = "name"
const val ATTR_OBJECT_BOUNDS = "bounds"
const val ATTR_OBJECT_ROTATION = "rotation"
const val ATTR_OBJECT_SCALE = "scale"
const val ATTR_OBJECT_VISIBLE = "visible"
const val ATTR_OBJECT_GROUPS = "groups"
const val ATTR_OBJECT_VIEW = "viewName"
const val ATTR_OBJECT_LAYER = "layerName"
const val ATTR_OBJECT_ORDER = "order"

const val ATTR_TRANSITION_CONDITION = "condition"
const val ATTR_TRANSITION_TARGET = "target"
const val ATTR_TRANSITION_ID = "transitionId"
const val ATTR_TRANSITION_ORIENTATION = "orientation"


const val TILED_PROP_STRING_TYPE = "string"
const val COMPOSITE_OBJECT_NAME_PREFIX = "Composite"
const val ATLAS_ASSET_NAME_PREFIX = "atlas_"
const val COLLISION_ASSET_NAME_PREFIX = "collisionMask_"

const val NAME_PROP = "name"
const val ATLAS_PROP = "atlas_file_path"
const val COLLISION_PROP = "collision_bitmask_file_path"

const val MATERIAL_PROP = "material"
const val MATERIAL_TYPE_PROP = "material_type"
const val CONTACT_TYPE_PROP = "contact_type"
const val CONTACT_FULL_PROP = "contact_full_rect"
const val CONTACT_X_PROP = "contact_mask_x"
const val CONTACT_Y_PROP = "contact_mask_y"
const val ATLAS_POS_PROP = "atlas_position"
const val ATLAS_X_PROP = "x"
const val ATLAS_Y_PROP = "y"
const val ATLAS_FLIP_PROP = "atlas_sprite_flip"
const val BLEND_PROP = "blend_mode"
const val TINT_PROP = "tint_color"
const val ASPECT_PROP = "tint"
const val ANIMATION_PROP = "animation"
const val RENDERER_PROP = "renderer"
const val SCALE_X = "scale_x"
const val SCALE_Y = "scale_y"

const val HORIZONTAL_VALUE = "horizontal"
const val VERTICAL_VALUE = "vertical"
const val FLAG_NAME_HORIZONTAL = "h"
const val FLAG_NAME_VERTICAL = "v"

const val PROP_ROOM_ACTIVATION_TASKS = "activation_tasks"
const val PROP_ROOM_DEACTIVATION_TASKS = "deactivation_tasks"
const val PROP_VALUE_TYPE_LAYER = "tilelayer"
const val PROP_VALUE_TYPE_OBJECT = "objectgroup"
const val PROP_LAYER_TILE_SETS = "layer_tilesets"
const val PROP_TILE_SET_REFS = "tileset_refs"
const val PROP_OBJECT_BUILD_TASK = "build_task"